seqtk subseq Whole_cleaned_aligned_merged_collapsed_qced_corrected.fasta Whole_demux_2reads2samples_squantifiltered.isoformIDs.txt > ../Whole_cleaned_aligned_merged_collapsed_qced_corrected_2reads2samples.fasta
seqtk subseq WholeTargeted_cleaned_aligned_merged_collapsed_qced_corrected.fasta WholeTargeted_demux_2reads2samples_squantifiltered.isoformIDs.txt > ../WholeTargeted_cleaned_aligned_merged_collapsed_qced_corrected_2reads2samples.fasta

grep -wF -f WholeTargeted_demux_2reads2samples_squantifiltered.isoformIDs.txt WholeTargeted_cleaned_aligned_merged_collapsed_qced_corrected.gtf > ../WholeTargeted_cleaned_aligned_merged_collapsed_qced_corrected_2reads2samples.gtf
grep -wF -f Whole_demux_2reads2samples_squantifiltered.isoformIDs.txt Whole_cleaned_aligned_merged_collapsed_qced_corrected.gtf > ../Whole_cleaned_aligned_merged_collapsed_qced_corrected_2reads2samples.gtf

grep -wF -f WholeTargeted_demux_2reads2samples_squantifiltered.isoformIDs.txt WholeTargeted_cleaned_aligned_merged_collapsed_qced_corrected.gtf.cds.gff > ../WholeTargeted_cleaned_aligned_merged_collapsed_qced_corrected_2reads2samples.gtf.cds.gff
grep -wF -f Whole_demux_2reads2samples_squantifiltered.isoformIDs.txt Whole_cleaned_aligned_merged_collapsed_qced_corrected.gtf.cds.gff > ../Whole_cleaned_aligned_merged_collapsed_qced_corrected_2reads2samples.gtf.cds.gff

grep -wF -f WholeTargeted_demux_2reads2samples_squantifiltered.isoformIDs.txt WholeTargeted_cleaned_aligned_merged_collapsed_qced_corrected.genePred > ../WholeTargeted_cleaned_aligned_merged_collapsed_qced_corrected_2reads2samples.genePred
grep -wF -f Whole_demux_2reads2samples_squantifiltered.isoformIDs.txt Whole_cleaned_aligned_merged_collapsed_qced_corrected.genePred > ../Whole_cleaned_aligned_merged_collapsed_qced_corrected_2reads2samples.genePred

head -n1 WholeTargeted_cleaned_aligned_merged_collapsed_qced_RulesFilter_classification.txt > ../WholeTargeted_cleaned_aligned_merged_collapsed_qced_RulesFilter_2reads2samples_classification.txt
grep -wF -f WholeTargeted_demux_2reads2samples_squantifiltered.isoformIDs.txt WholeTargeted_cleaned_aligned_merged_collapsed_qced_RulesFilter_classification.txt >> ../WholeTargeted_cleaned_aligned_merged_collapsed_qced_RulesFilter_2reads2samples_classification.txt
head -n1 Whole_cleaned_aligned_merged_collapsed_qced_RulesFilter_classification.txt > ../Whole_cleaned_aligned_merged_collapsed_qced_RulesFilter_2reads2samples_classification.txt
grep -wF -f Whole_demux_2reads2samples_squantifiltered.isoformIDs.txt Whole_cleaned_aligned_merged_collapsed_qced_RulesFilter_classification.txt >> ../Whole_cleaned_aligned_merged_collapsed_qced_RulesFilter_2reads2samples_classification.txt

grep -wF -f Whole_demux_2reads2samples_squantifiltered.isoformIDs.txt Whole_cleaned_aligned_merged_collapsed_qced_filtered_inclusion-list.txt >> ../Whole_cleaned_aligned_merged_collapsed_qced_2reads2samples_filtered_inclusion-list.txt
grep -wF -f WholeTargeted_demux_2reads2samples_squantifiltered.isoformIDs.txt WholeTargeted_cleaned_aligned_merged_collapsed_qced_filtered_inclusion-list.txt >> ../WholeTargeted_cleaned_aligned_merged_collapsed_qced_2reads2samples_filtered_inclusion-list.txt

head -n1 WholeTargeted_cleaned_aligned_merged_collapsed_qced_junctions.txt > ../WholeTargeted_cleaned_aligned_merged_collapsed_qced_2reads2samples_junctions.txt
grep -wF -f WholeTargeted_demux_2reads2samples_squantifiltered.isoformIDs.txt WholeTargeted_cleaned_aligned_merged_collapsed_qced_junctions.txt >> ../WholeTargeted_cleaned_aligned_merged_collapsed_qced_2reads2samples_junctions.txt
head -n1 Whole_cleaned_aligned_merged_collapsed_qced_junctions.txt > ../Whole_cleaned_aligned_merged_collapsed_qced_2reads2samples_junctions.txt
grep -wF -f Whole_demux_2reads2samples_squantifiltered.isoformIDs.txt Whole_cleaned_aligned_merged_collapsed_qced_junctions.txt >> ../Whole_cleaned_aligned_merged_collapsed_qced_2reads2samples_junctions.txt
