#!/bin/bash
#SBATCH --export=ALL # export all environment variables to the batch job
#SBATCH -D .
#SBATCH -p mrcq # submit to the parallel queue
#SBATCH --time=144:00:00 # maximum walltime for the job e.g. 01:00:00
#SBATCH -A Research_Project-MRC148213 # research project to submit under
#SBATCH --nodes=1 # specify number of nodes
#SBATCH --ntasks-per-node=16 # specify number of processors per node
#SBATCH --mem=200G # specify bytes of memory to reserve
#SBATCH --mail-type=END # send email at job completion
#SBATCH --mail-user=rb520@exeter.ac.uk # email address

#This is Minimap2 (https://github.com/lh3/minimap2). It is aligns your reads to the reference genome.
#The input is the 'trimmed.fasta' file from the Orientation file (if you are doing targeted transcriptome).
#The input is the fastq file if it is whole transcriptome data. 
#After the alignment it is straight away sorted into a BAM file (temporary files will be generated).
#You require a reference genome file
#Options to include are the -ax splice (for long read splicing) and --MD (for annotation purposes downstream) options. 


source "/lustre/home/rb520/miniconda3/etc/profile.d/conda.sh"
conda activate tools

REF=PATH/Hg38.fa
#REF=PATH/gorGor6.fa
#REF=PATH/mm10.fa

#Path to project where fastq files are
PROJECT="/lustre/projects/Research_Project-MRC190311/longReadSeq/ONTRNA/Targeted_transcriptome/10780_batch1/P0059_20220813_10780/P0059_20220813_10780/Batch1/20220813_1259_3G_PAM33351_84e820b3/"

cd ${PROJECT} 

#Use the for loop for targeted analysis

for folder in {00..01}; do
	cd "Porechop_"$folder""
	echo "Porechop_"$folder""

	for bc in {01..02}; do
       
		minimap2 -ax splice --MD -t 48 ${REF} BC"$bc"_trimmed.fasta | samtools sort -o BC"$bc"_aligned.bam -T "reads"$bc".tmp"

	done
	cd ..
done

#Use if you are just aligning a single file or fastq files from whole transcriptome data

#minimap2 -ax splice --MD -t 48 ${REF} ${PROJECT}/fastq | samtools sort -o aligned.bam -T reads.tmp


